/******************************************************************************/
/* This file has been generated by the uGFX-Studio                            */
/*                                                                            */
/* http://ugfx.org                                                            */
/******************************************************************************/

#ifndef _GUI_H_
#define _GUI_H_

#include "gfx.h"

// Widget groups
#define GROUP_DEFAULT 0

// GListeners
extern GListener glistener;

// GHandles
extern GHandle ghContainerPage0;
extern GHandle ghContainer1;
extern GHandle ghButton1_2;
extern GHandle ghButton1_1;
extern GHandle ghButton1;
extern GHandle ghTextedit1;

// Function Prototypes
void guiCreate(void);
void guiShowPage(unsigned pageIndex);
void guiEventLoop(void);

#endif /* _GUI_H_ */

